/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FusionMarket.VIEW;

/**
 *
 * @author cedup
 */
public class CadastroUsuario_VIEW extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroUsuario_VIEW
     */
    public CadastroUsuario_VIEW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setBorder(null);
        setMaximumSize(new java.awt.Dimension(966, 580));
        setMinimumSize(new java.awt.Dimension(966, 580));
        setPreferredSize(new java.awt.Dimension(966, 580));
        getContentPane().setLayout(null);

        jLabel1.setMaximumSize(new java.awt.Dimension(950, 550));
        jLabel1.setMinimumSize(new java.awt.Dimension(950, 550));
        jLabel1.setPreferredSize(new java.awt.Dimension(950, 550));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 950, 550);

        setBounds(-2, -23, 966, 580);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
