/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FusionMarket.VIEW;

/**
 *
 * @author User
 */
public class MinhaLoja_VIEW extends javax.swing.JInternalFrame {

    /**
     * Creates new form MinhaLoja_VIEW2
     */
    public MinhaLoja_VIEW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B_Adicionar = new javax.swing.JLabel();
        Painei_MinhaLoja = new javax.swing.JLabel();
        B_Voltar = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        B_Adicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FusionMarket/IMAGENS/Botão_AdicionarProduto.png"))); // NOI18N
        B_Adicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_AdicionarMouseClicked(evt);
            }
        });
        getContentPane().add(B_Adicionar);
        B_Adicionar.setBounds(55, 114, 160, 150);

        Painei_MinhaLoja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FusionMarket/IMAGENS/Painei_MinhaLoja.png"))); // NOI18N
        Painei_MinhaLoja.setMaximumSize(new java.awt.Dimension(950, 550));
        Painei_MinhaLoja.setMinimumSize(new java.awt.Dimension(950, 550));
        Painei_MinhaLoja.setPreferredSize(new java.awt.Dimension(950, 550));
        getContentPane().add(Painei_MinhaLoja);
        Painei_MinhaLoja.setBounds(0, 0, 950, 550);

        B_Voltar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        B_Voltar.setForeground(new java.awt.Color(255, 255, 255));
        B_Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FusionMarket/IMAGENS/Botão_Voltar.png"))); // NOI18N
        B_Voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_VoltarMouseClicked(evt);
            }
        });
        getContentPane().add(B_Voltar);
        B_Voltar.setBounds(22, 20, 60, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_AdicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_AdicionarMouseClicked
        AdicionarProduto_VIEW Tela_AdicionarProduto = new AdicionarProduto_VIEW();
        Tela_AdicionarProduto.setVisible(true);
    }//GEN-LAST:event_B_AdicionarMouseClicked

    private void B_VoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_VoltarMouseClicked
        this.dispose();
    }//GEN-LAST:event_B_VoltarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel B_Adicionar;
    private javax.swing.JLabel B_Voltar;
    private javax.swing.JLabel Painei_MinhaLoja;
    // End of variables declaration//GEN-END:variables
}
